// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ws_Agenda.Services;

#nullable disable

namespace Ws_Agenda.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220612155737_fix_table")]
    partial class fix_table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ws_Agenda.Models.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"), 1L, 1);

                    b.Property<string>("User_Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("User_Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("User_Id");

                    b.ToTable("tb_users");
                });

            modelBuilder.Entity("Ws_Agenda.Models.User_Registrer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("User_BirthDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("User_LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("User_Phone")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<byte[]>("User_photo")
                        .IsUnicode(false)
                        .HasColumnType("varbinary");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("tb_user_Registred");
                });

            modelBuilder.Entity("Ws_Agenda.Models.User_Registrer", b =>
                {
                    b.HasOne("Ws_Agenda.Models.User", "User")
                        .WithOne("User_Registrer")
                        .HasForeignKey("Ws_Agenda.Models.User_Registrer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ws_Agenda.Models.User", b =>
                {
                    b.Navigation("User_Registrer");
                });
#pragma warning restore 612, 618
        }
    }
}
